### ISSUE TITLE
Why kafka?

### ISSUE THREAD

**Issue by OrlovDiga** [Luka-Spa/SwipeRight#4]
Hello, Luka, why do you use kafka in profile service?

**Comment by Luka-Spa** [comment]
This project was actually a school assignment, which had the requirement to be designed with a certain architecture. Kafka is a really capable service bus which is commonly used in an event-driven microservices architecture (which I opted for). So whenever a new profile is created in the profile service an event is emitted to kafka. Other services can subscribe to this event and use it however.
